-- Migration Menu & Recettes
-- Les tables recipes et recipe_ingredients existent déjà dans Supabase.
-- Aucune création de table nécessaire.
--
-- Structure utilisée :
--
-- recipes (plats du menu)
--   id UUID PK
--   restaurant_id UUID → restaurants(id)
--   dish_name TEXT
--   sell_price NUMERIC
--   category TEXT
--   is_active BOOLEAN DEFAULT true
--   created_at TIMESTAMPTZ
--
-- recipe_ingredients (ingrédients par plat)
--   id UUID PK
--   recipe_id UUID → recipes(id) ON DELETE CASCADE
--   product_id UUID → products(id) ON DELETE CASCADE
--   quantity NUMERIC
--
-- products (stock)
--   id UUID PK
--   restaurant_id UUID
--   name TEXT
--   unit TEXT
--   buy_price NUMERIC
--   stock_qty NUMERIC
--   min_threshold NUMERIC
--   category TEXT
--   created_at / updated_at
--
-- RLS déjà en place sur toutes ces tables.
-- Rien à exécuter.
